### ISSUE TITLE
Add Language Support (Internationalization)

### ISSUE THREAD

**Issue by Archna-1** [zorazrr/activ-card#29]
## Description
Currently, the site is only in English. Add translations for all static text on the site. We don't have designs for internationalization, so the styling and placement of the button is up to you.

## Todos

- [ ] Add dropdown or icon for translations to header (and potentially the footer of the landing page)
- [ ] Translate landing page
- [ ] Translate dashboard
- [ ] Translate set creation page
- [ ] Translate set page (not the cards)
- [ ] Translate pomodoro page

## Useful links

- https://react.i18next.com/latest/usetranslation-hook
- https://www.figma.com/file/NmP6r9rMYcnWbKqp7klBOZ/ActiveCard?type=design&node-id=49-93&mode=design&t=996r1fvyHFAeo3Mf-0
