### ISSUE TITLE
Fix Image Prompting

### ISSUE THREAD

**Issue by Archna-1** [zorazrr/activ-card#30]
## Description
Right now, image prompting during the Pomodoro break returns abstract art, but we want it to mirror what the user has drawn a bit better. We'll rework our pipeline for image prompting and generation. We'll ask ChatGPT to describe the input image, generate an image based off the description, and return the image to the user.

## Todos

- [ ] Implement image generation workflow: Image  → “Describe this image to me” →  ChatGPT Output → “Generate an image with this description” → Image (sticker)
- [ ] Test to make sure that images generated are child-friendly
- [ ] Be sure to pass image into backend from frontend without any intermediate save state.

## Useful links

- https://platform.openai.com/docs/guides/vision
- https://platform.openai.com/docs/guides/images/introduction?context=node
