### ISSUE TITLE
Fix Pomodoro Logic and Access

### ISSUE THREAD

**Issue by Archna-1** [zorazrr/activ-card#38]
## Description
Right now, the pomodoro break is hardcoded to display after 3 cards. We want it to show up every x cards, and we want to make sure that it does not "replace" showing one of the cards and the student can study all cards (instead of displaying the 4th card, it currently just displays the canvas).

Additionally, users can press the back button and take their pomodoro break again. Ensure that if users press the "back" button, they cannot go back to a break.

## Todos

- [ ] Fix pomodoro break rendering logic to avoid "replacing" cards
  - This will likely fix being able to take breaks again
- [ ] Render pomodoro break every x cards
- [ ] Fix back button to avoid letting users take breaks again

## Useful links

- https://github.com/zorazrr/activ-card/blob/cf036f081481e50795d887c11480ed881b6fcffc/src/pages/set/%5Bid%5D.tsx#L54
